runtime: go111
#api_version: go1

# NOTE: Enable for production
instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 5000ms
  max_concurrent_requests: 20

handlers:
- url: /.*
  script: auto
